name: Run Unit and E2E Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: women-clothes
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    env:
      DATABASE_URL: postgresql://postgres:123456@localhost:5432/women-clothes?schema=public
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Setup .env.test
        run: |
          echo "DATABASE_URL=postgresql://postgres:123456@localhost:5432/women-clothes?schema=public" > .env.test
          cp .env.test .env

      - name: Deploy DB schema
        run: npx prisma migrate deploy || npx prisma db push

      - name: Install Browsers
        run: npx playwright install --with-deps   
        
      - name: Build the app
        run: npm run build

      - name: Start the app & run E2E tests
        run: |
          npx start-server-and-test preview http://localhost:3000 'npm run test:e2e'
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        timeout-minutes: 10

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30